services:
  db:
    image: mysql:9.7
    container_name: base_datos
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: citas_medicas
    ports:
      - 3307:3306
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql                   
    secrets:
      - db_password
  webdatos:
    container_name: web_datos
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./Data/public:/var/www/html/public
      - ./Data/src:/var/www/html/src
    build:
      context: .
      dockerfile: ./Data/Dockerfile
    ports:
      - 8080:80
    secrets:
      - db_password
  webnegocio:
    container_name: web_negocio
    volumes:
      - ./Business/public:/var/www/html/public
      - ./Business/src:/var/www/html/src
    build:
      context: .
      dockerfile: ./Business/Dockerfile
    ports:
      - 9090:80
    secrets:
      - db_password
secrets:
  db_password:
    file: ./db_password.txt